version: "3.8"
services:
    #PHP service
        php:
            build:
                context: .
                target: php
                args:
                    - APP_ENV={$APP_ENV}
            container_name: php-app
            environment:
                - APP_ENV={$APP_ENV}
                - CONTAINER_ROLE=app
            working_dir: /var/www
            volumes:
                - ./:/var/www
            ports:
                - 8000:8000
            links:
                - mysql
            depends_on:
                - mysql

    # Database service
        mysql:
            image: mysql:8.0
            container_name: mysql
            ports:
                - "3306:3306"
            environment:
                - MYSQL_DATABASE=${DB_DATABASE}
                - MYSQL_USER=${DB_USERNAME}
                - MYSQL_PASSWORD=${DB_PASSWORD}
                - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            volumes:
                - db-data:/var/lib/mysql

volumes:
  db-data: ~


